const ActionTypes = {
  // AUTH
  LOGIN: 'LOGIN',
  TRIP: 'TRIP',
  FAVORITE_TRIP: 'FAVORITE_TRIP',
  GET_USER_TRIPS: 'GET_USER_TRIPS',
  NEARBY_ACTIVITIES: 'NEARBY_ACTIVITIES',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
}

export default ActionTypes
